// Popular
export const LOAD_DATA_POPULAR = 'LOAD_DATA_POPULAR';
export const GO_POPULAR = 'GO_POPULAR';
export const CHANGE_SHOW_LIST = 'CHANGE_SHOW_LIST';
export const ADD_FAVORITES = 'ADD_FAVORITES';
export const GET_FAVORITES = 'GET_FAVORITES';