// Popular
export const LOAD_DATA_POPULAR = 'LOAD_DATA_POPULAR';
export const GO_POPULAR = 'GO_POPULAR';
export const CHANGE_SHOW_LIST = 'CHANGE_SHOW_LIST';
export const ADD_FAVORITES = 'ADD_FAVORITES';
export const GET_FAVORITES = 'GET_FAVORITES';
export const REMOVE_FAVORITE = 'REMOVE_FAVORITE';
export const CHANGE_TITLE = 'CHANGE_TITLE';
export const CHANGE_SEARCH_BUTTON = 'CHANGE_SEARCH_BUTTON'  ;
//NowPlaying
export const LOAD_DATA_NOW_PLAYING = 'LOAD_DATA_NOW_PLAYING';
//TopRated
export const LOAD_DATA_TOP_RATED = 'LOAD_DATA_TOP_RATED';
//Upcoming
export const LOAD_DATA_UPCOMING = 'LOAD_DATA_UPCOMING';
//detail
export const LOAD_DATA_DETAIL = 'LOAD_DATA_DETAIL';
//credit
export const LOAD_DATA_CREDIT = 'LOAD_DATA_CREDIT';
//reminder 
export const ADD_REMINDER = 'ADD_REMINDER';
export const LOAD_REMINDER = 'LOAD_REMINDER';
export const REMOVE_REMINDER = 'REMOVE_REMINDER';